# service-backendpolicy.yaml
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
spec:
  selector:
    app: iapgw-webapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: app2
spec:
  selector:
    app: iapgw-webapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: app1-backend-policy
  namespace: app1
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-oauth-secret
      clientID: "REPLACE-WITH-CLIENT-ID"
  targetRef:
    group: ""
    kind: Service
    name: app1-service
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: app2-backend-policy
  namespace: app2
spec:
  default:
    iap:
      enabled: true
      oauth2ClientSecret:
        name: iap-oauth-secret
      clientID: "REPLACE-WITH-CLIENT-ID"
  targetRef:
    group: ""
    kind: Service
    name: app2-service
